using Microsoft.Win32; using System.Windows.Input; using System.Windows.Threading; using System.Runtime.InteropServices; using System.Text; using System.Windows; using System.Windows.Controls; using System.Windows.Interop; using System.Windows.Media; using System.Windows.Shapes; using TagWriter.Models; using TagWriter.Services;
namespace TagWriter;
public partial class MainWindow:Window {
 ProjectDocument _document=ProjectDocument.CreateSample(); string? _path; Scene? _scene; EntityCard? _card; bool _loading; bool _dark=true; bool _leftCollapsed=false,_rightCollapsed=false; double _leftWidth=250,_rightWidth=310; bool _paperMode=false,_paperFit=true; Button? _activeActivityButton; double _paperZoom=1.0; const double PaperCell=34,PaperMargin=42;
 readonly List<ManuscriptPaperSurface> _paperSurfaces=new(); DispatcherTimer? _paperRenderTimer; bool _paperDragging; int _paperDragAnchorText; int? _paperKeyboardSelectionAnchor; bool _treeEditMode; Point _treeDragStart; object? _treeDragItem; readonly HashSet<object> _treeEditSelection=new(); readonly Stack<Action> _treeUndo=new(); sealed record TreeDeleteSnapshot(List<(Chapter chapter,int index)> Chapters,List<(Scene scene,Chapter chapter,int index)> Scenes);
 public MainWindow(){InitializeComponent();SourceInitialized+=(_,_)=>ApplyWindowChromeTheme();Loaded+=(_,_)=>{InitializeEditorPreferences();_paperRenderTimer=new DispatcherTimer(DispatcherPriority.Render){Interval=TimeSpan.FromMilliseconds(16)};_paperRenderTimer.Tick+=(_,_)=>{_paperRenderTimer.Stop();RenderManuscriptPaper();};};RefreshAll();SelectFirstScene();ApplyTheme(_document.Settings.Theme!="light");}
 void InitializeEditorPreferences(){var preferred=new[]{"Malgun Gothic","Batang","Noto Sans KR","Noto Serif KR","Segoe UI","Arial","Times New Roman","Georgia"};var installed=Fonts.SystemFontFamilies.ToDictionary(f=>f.Source,StringComparer.OrdinalIgnoreCase);var fonts=preferred.Where(installed.ContainsKey).Select(n=>installed[n]).ToList();if(!fonts.Any(f=>f.Source.Equals(_document.Settings.EditorFontFamily,StringComparison.OrdinalIgnoreCase))){try{fonts.Insert(0,new FontFamily(_document.Settings.EditorFontFamily));}catch{}}FontFamilyBox.ItemsSource=fonts;FontFamilyBox.SelectedItem=fonts.FirstOrDefault(f=>f.Source.Equals(_document.Settings.EditorFontFamily,StringComparison.OrdinalIgnoreCase))??fonts.FirstOrDefault();FontSizeBox.ItemsSource=new double[]{10,11,12,13,14,15,16,17,18,20,22,24,26,28,32};FontSizeBox.SelectedItem=FontSizeBox.Items.Cast<double>().OrderBy(v=>Math.Abs(v-_document.Settings.EditorFontSize)).First();ApplyEditorPreferences();}
 void ApplyEditorPreferences(){try{Editor.FontFamily=new FontFamily(_document.Settings.EditorFontFamily);}catch{Editor.FontFamily=new FontFamily("Malgun Gothic");}Editor.FontSize=Math.Clamp(_document.Settings.EditorFontSize,9,48);Editor.SetValue(TextBlock.LineHeightProperty,Math.Max(Editor.FontSize*1.7,Editor.FontSize+6));}
 void FontFamilyBox_SelectionChanged(object s,SelectionChangedEventArgs e){if(FontFamilyBox.SelectedItem is FontFamily f){_document.Settings.EditorFontFamily=f.Source;ApplyEditorPreferences();}}
 void FontSizeBox_SelectionChanged(object s,SelectionChangedEventArgs e){if(FontSizeBox.SelectedItem is double size){_document.Settings.EditorFontSize=size;ApplyEditorPreferences();}}
 void RefreshAll(){RefreshTree();RefreshIdeas();UpdateStatus();Title=$"{_document.Project.Title} — TagWriter";}
 void RefreshTree(){
  ProjectTree.Items.Clear(); var manuscript=new TreeViewItem{Header=MakeManuscriptHeader(),IsExpanded=true,Tag="manuscript",FontWeight=FontWeights.Bold,FontSize=15};
  foreach(var chapter in _document.Chapters.OrderBy(x=>x.Order)){var cn=new TreeViewItem{Header=MakeTreeHeader(chapter.Title,chapter,()=>AddSceneToChapter(chapter)),IsExpanded=true,Tag=chapter,FontWeight=FontWeights.Normal,FontSize=13};foreach(var scene in chapter.Scenes.OrderBy(x=>x.Order))cn.Items.Add(new TreeViewItem{Header=MakeTreeHeader(scene.Title,scene,()=>AddSceneAfter(scene)),Tag=scene,FontWeight=FontWeights.Normal,FontSize=13});manuscript.Items.Add(cn);} ProjectTree.Items.Add(manuscript);
  var cards=new TreeViewItem{Header="설정 카드",IsExpanded=true,FontWeight=FontWeights.Bold,FontSize=15}; foreach(CardType type in Enum.GetValues<CardType>()){var g=new TreeViewItem{Header=TypeName(type),IsExpanded=true,FontWeight=FontWeights.Normal,FontSize=13};foreach(var card in _document.Cards.Where(x=>x.Type==type).OrderBy(x=>x.Name))g.Items.Add(new TreeViewItem{Header=card.Name,Tag=card,FontWeight=FontWeights.Normal,FontSize=13});cards.Items.Add(g);} ProjectTree.Items.Add(cards);ProjectTree.Items.Add(new TreeViewItem{Header="◆ 관계맵",Tag="mindmap",FontWeight=FontWeights.Bold,FontSize=15,Margin=new Thickness(-16,0,0,0)});
 }
 FrameworkElement MakeManuscriptHeader(){var grid=new Grid{HorizontalAlignment=HorizontalAlignment.Stretch};grid.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(1,GridUnitType.Star)});grid.ColumnDefinitions.Add(new ColumnDefinition{Width=GridLength.Auto});var title=new TextBlock{Text=_document.Project.Title,TextWrapping=TextWrapping.Wrap,VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(0,0,8,0)};var add=new Button{Content="새 챕터",Padding=new Thickness(7,3,7,3),Margin=new Thickness(4,0,0,0),FontSize=11,FontWeight=FontWeights.Normal,VerticalAlignment=VerticalAlignment.Top,ToolTip="새 챕터 추가"};Grid.SetColumn(title,0);Grid.SetColumn(add,1);add.Click+=(_,e)=>{AddChapter();e.Handled=true;};grid.Children.Add(title);grid.Children.Add(add);return grid;}
 FrameworkElement MakeTreeHeader(string title,object item,Action add){var panel=new StackPanel{Orientation=Orientation.Horizontal};if(_treeEditMode){var check=new CheckBox{VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(0,0,6,0),IsChecked=_treeEditSelection.Contains(item)};check.Checked+=(_,_)=>_treeEditSelection.Add(item);check.Unchecked+=(_,_)=>_treeEditSelection.Remove(item);panel.Children.Add(check);}var label=new TextBlock{Text=title,VerticalAlignment=VerticalAlignment.Center};panel.Children.Add(label);if(!_treeEditMode){var plus=new Button{Content="+",Width=22,Height=22,Padding=new Thickness(0),Margin=new Thickness(8,0,0,0),Background=Brushes.Transparent,BorderThickness=new Thickness(0),Foreground=(Brush)FindResource("Muted"),FontSize=16,FontWeight=FontWeights.Normal,Cursor=Cursors.Hand,ToolTip="추가"};plus.MouseEnter+=(_,_)=>{plus.FontWeight=FontWeights.Bold;plus.Foreground=(Brush)FindResource("Text");};plus.MouseLeave+=(_,_)=>{plus.FontWeight=FontWeights.Normal;plus.Foreground=(Brush)FindResource("Muted");};plus.Click+=(_,e)=>{add();e.Handled=true;};panel.Children.Add(plus);}return panel;}
 void TreeEdit_Click(object s,RoutedEventArgs e){_treeEditMode=true;_treeEditSelection.Clear();TreeEditButton.Visibility=Visibility.Collapsed;TreeDeleteButton.Visibility=Visibility.Visible;TreeUndoButton.Visibility=Visibility.Visible;TreeEditDoneButton.Visibility=Visibility.Visible;RefreshTree();}
 void TreeEditDone_Click(object s,RoutedEventArgs e){_treeEditMode=false;_treeEditSelection.Clear();TreeEditButton.Visibility=Visibility.Visible;TreeDeleteButton.Visibility=Visibility.Collapsed;TreeUndoButton.Visibility=Visibility.Collapsed;TreeEditDoneButton.Visibility=Visibility.Collapsed;RefreshTree();}
 void TreeDelete_Click(object s,RoutedEventArgs e){var chapters=_treeEditSelection.OfType<Chapter>().ToList();var scenes=_treeEditSelection.OfType<Scene>().Where(sc=>!chapters.Any(ch=>ch.Scenes.Contains(sc))).ToList();if(chapters.Count==0&&scenes.Count==0)return;var count=chapters.Count+scenes.Count;if(MessageBox.Show($"선택한 {count}개 항목을 삭제할까?","선택 삭제",MessageBoxButton.YesNo,MessageBoxImage.Warning)!=MessageBoxResult.Yes)return;PersistEditor();var snapCh=chapters.Select(ch=>(ch,_document.Chapters.IndexOf(ch))).ToList();var snapSc=scenes.Select(sc=>{var ch=_document.Chapters.First(x=>x.Scenes.Contains(sc));return(sc,ch,ch.Scenes.IndexOf(sc));}).ToList();var snapshot=new TreeDeleteSnapshot(snapCh,snapSc);_treeUndo.Push(()=>{foreach(var (ch,index) in snapshot.Chapters.OrderBy(x=>x.index))_document.Chapters.Insert(Math.Min(index,_document.Chapters.Count),ch);foreach(var (sc,ch,index) in snapshot.Scenes.OrderBy(x=>x.index))if(_document.Chapters.Contains(ch)&&!ch.Scenes.Contains(sc))ch.Scenes.Insert(Math.Min(index,ch.Scenes.Count),sc);NormalizeTreeOrder();});foreach(var sc in scenes){var ch=_document.Chapters.FirstOrDefault(x=>x.Scenes.Contains(sc));ch?.Scenes.Remove(sc);if(_scene==sc)_scene=null;}foreach(var ch in chapters){if(_scene!=null&&ch.Scenes.Contains(_scene))_scene=null;_document.Chapters.Remove(ch);}NormalizeTreeOrder();_treeEditSelection.Clear();TreeUndoButton.IsEnabled=true;RefreshTree();if(_scene==null)SelectFirstScene();UpdateStatus();}
 void TreeUndo_Click(object s,RoutedEventArgs e){if(_treeUndo.Count==0)return;_treeUndo.Pop()();TreeUndoButton.IsEnabled=_treeUndo.Count>0;RefreshTree();UpdateStatus();}
 void NormalizeTreeOrder(){var chapters=_document.Chapters.OrderBy(x=>x.Order).ToList();for(int i=0;i<chapters.Count;i++){chapters[i].Order=i+1;var scenes=chapters[i].Scenes.OrderBy(x=>x.Order).ToList();for(int j=0;j<scenes.Count;j++)scenes[j].Order=j+1;}}
 void AddChapter(){PersistEditor();var n=_document.Chapters.Count+1;var ch=new Chapter{Title=NextChapterTitle(n),Order=n};ch.Scenes.Add(new Scene{Title="Scene 1",Order=1});_document.Chapters.Add(ch);RefreshTree();ShowScene(ch.Scenes[0]);}
 void AddChapterAfter(Chapter chapter){PersistEditor();var ordered=_document.Chapters.OrderBy(x=>x.Order).ToList();var pos=ordered.IndexOf(chapter)+1;var ch=new Chapter{Title=NextChapterTitle(_document.Chapters.Count+1),Order=pos+1};ch.Scenes.Add(new Scene{Title="Scene 1",Order=1});_document.Chapters.Add(ch);for(int i=0;i<ordered.Count;i++)ordered[i].Order=i<pos?i+1:i+2;RefreshTree();ShowScene(ch.Scenes[0]);}
 void AddSceneToChapter(Chapter chapter){PersistEditor();var sc=new Scene{Title=$"Scene {chapter.Scenes.Count+1}",Order=chapter.Scenes.Count+1};chapter.Scenes.Add(sc);RefreshTree();ShowScene(sc);}
 void AddSceneAfter(Scene scene){var chapter=_document.Chapters.FirstOrDefault(x=>x.Scenes.Contains(scene));if(chapter==null)return;PersistEditor();var ordered=chapter.Scenes.OrderBy(x=>x.Order).ToList();var pos=ordered.IndexOf(scene)+1;var sc=new Scene{Title=$"Scene {chapter.Scenes.Count+1}",Order=pos+1};chapter.Scenes.Add(sc);for(int i=0;i<ordered.Count;i++)ordered[i].Order=i<pos?i+1:i+2;RefreshTree();ShowScene(sc);}
 static string TypeName(CardType t)=>t switch{CardType.Character=>"캐릭터",CardType.Location=>"장소",CardType.Item=>"물건",CardType.Event=>"사건",_=>t.ToString()};
 void SelectFirstScene(){var s=_document.Chapters.OrderBy(x=>x.Order).SelectMany(x=>x.Scenes.OrderBy(y=>y.Order)).FirstOrDefault();if(s!=null)ShowScene(s);}
 void ProjectTree_MouseDoubleClick(object s,System.Windows.Input.MouseButtonEventArgs e){if(ProjectTree.SelectedItem is not TreeViewItem i)return;if(i.Tag as string=="manuscript"){RenameProject();e.Handled=true;}else if(i.Tag is Chapter chapter){RenameChapter(chapter);e.Handled=true;}else if(i.Tag is Scene scene){RenameScene(scene);e.Handled=true;}}
 void RenameChapter(Chapter chapter){if(ShowRenameDialog("장 제목 변경",chapter.Title,out var title)){chapter.Title=title;_document.Project.UpdatedAt=DateTimeOffset.Now;RefreshTree();if(_scene!=null)ShowScene(_scene);}}
 void RenameScene(Scene scene){if(ShowRenameDialog("씬 이름 변경",scene.Title,out var title)){scene.Title=title;_document.Project.UpdatedAt=DateTimeOffset.Now;RefreshTree();ShowScene(scene);}}
 void ProjectTree_PreviewMouseLeftButtonDown(object s,MouseButtonEventArgs e){_treeDragStart=e.GetPosition(ProjectTree);_treeDragItem=FindTreeItem(e.OriginalSource as DependencyObject)?.Tag;}
 void ProjectTree_PreviewMouseMove(object s,MouseEventArgs e){if(!_treeEditMode||e.LeftButton!=MouseButtonState.Pressed||_treeDragItem is not (Scene or Chapter))return;var p=e.GetPosition(ProjectTree);if(Math.Abs(p.X-_treeDragStart.X)<SystemParameters.MinimumHorizontalDragDistance&&Math.Abs(p.Y-_treeDragStart.Y)<SystemParameters.MinimumVerticalDragDistance)return;DragDrop.DoDragDrop(ProjectTree,_treeDragItem,DragDropEffects.Move);_treeDragItem=null;}
 void ProjectTree_DragOver(object s,DragEventArgs e){var movable=e.Data.GetDataPresent(typeof(Scene))||e.Data.GetDataPresent(typeof(Chapter));e.Effects=_treeEditMode&&movable?DragDropEffects.Move:DragDropEffects.None;e.Handled=true;}
 void ProjectTree_Drop(object s,DragEventArgs e){if(!_treeEditMode)return;var target=FindTreeItem(e.OriginalSource as DependencyObject)?.Tag;if(e.Data.GetData(typeof(Scene)) is Scene scene)MoveScene(scene,target);else if(e.Data.GetData(typeof(Chapter)) is Chapter chapter)MoveChapter(chapter,target);e.Handled=true;}
 TreeViewItem? FindTreeItem(DependencyObject? d){while(d!=null&&d is not TreeViewItem)d=VisualTreeHelper.GetParent(d);return d as TreeViewItem;}
 void MoveScene(Scene scene,object? target){var from=_document.Chapters.FirstOrDefault(x=>x.Scenes.Contains(scene));if(from==null)return;Chapter? to=null;int insert=0;if(target is Chapter tch){to=tch;insert=tch.Scenes.Count;}else if(target is Scene tsc){to=_document.Chapters.FirstOrDefault(x=>x.Scenes.Contains(tsc));if(to!=null)insert=to.Scenes.OrderBy(x=>x.Order).ToList().IndexOf(tsc)+1;}if(to==null||target==scene)return;var oldIndex=from.Scenes.IndexOf(scene);from.Scenes.Remove(scene);insert=Math.Min(insert,to.Scenes.Count);to.Scenes.Insert(insert,scene);NormalizeTreeOrder();_treeUndo.Push(()=>{to.Scenes.Remove(scene);from.Scenes.Insert(Math.Min(oldIndex,from.Scenes.Count),scene);NormalizeTreeOrder();});TreeUndoButton.IsEnabled=true;RefreshTree();}
 void MoveChapter(Chapter chapter,object? target){if(target is not Chapter tch||tch==chapter)return;var old=_document.Chapters.IndexOf(chapter);_document.Chapters.Remove(chapter);var index=_document.Chapters.IndexOf(tch);_document.Chapters.Insert(Math.Max(0,index),chapter);NormalizeTreeOrder();_treeUndo.Push(()=>{_document.Chapters.Remove(chapter);_document.Chapters.Insert(Math.Min(old,_document.Chapters.Count),chapter);NormalizeTreeOrder();});TreeUndoButton.IsEnabled=true;RefreshTree();}

 void ProjectTree_SelectedItemChanged(object s,RoutedPropertyChangedEventArgs<object> e){if(e.NewValue is not TreeViewItem i)return;if(i.Tag is Scene sc)ShowScene(sc);else if(i.Tag is EntityCard c)ShowCard(c);else if(i.Tag as string=="mindmap")ShowMindMap();}
 void ShowScene(Scene s){SetActivityButton(ManuscriptModeButton);PersistEditor();_scene=s;_card=null;_loading=true;Editor.IsReadOnly=false;Editor.Text=s.Content;PaperInput.Text=s.Content;var ch=_document.Chapters.FirstOrDefault(x=>x.Scenes.Contains(s));EditorTitle.Text=$"{_document.Project.Title}  |  {ch?.Title??""}  |  {s.Title}";EditorSubtitle.Text="원고 편집";_loading=false;EditorView.Visibility=Visibility.Visible;MindMapView.Visibility=Visibility.Collapsed;RefreshOccurrencesForScene();UpdateStatus();}
 void ShowCard(EntityCard c){_card=c;CardName.Text=c.Name;CardTypeText.Text=TypeName(c.Type);CardDescription.Text=c.Description;CardAliases.Text=string.Join(Environment.NewLine,c.Aliases);RefreshOccurrences(c);RefreshRelations(c);}
 void PersistEditor(){if(_scene!=null&&!_loading)_scene.Content=Editor.Text;}
 void Editor_TextChanged(object s,TextChangedEventArgs e){if(_loading||_scene==null)return;_scene.Content=Editor.Text;UpdateStatus();RefreshOccurrencesForScene();}
 void RefreshOccurrencesForScene(){if(_scene==null)return;OccurrenceList.ItemsSource=_document.Cards.Where(c=>c.Aliases.Append(c.Name).Any(a=>!string.IsNullOrWhiteSpace(a)&&_scene.Content.Contains(a,StringComparison.CurrentCultureIgnoreCase))).Select(c=>$"#{c.Name} · 현재 장면에서 발견").ToList();}
 void RefreshOccurrences(EntityCard c){var terms=c.Aliases.Append(c.Name).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct().ToArray();var hits=new List<string>();foreach(var ch in _document.Chapters.OrderBy(x=>x.Order))foreach(var sc in ch.Scenes.OrderBy(x=>x.Order))foreach(var line in sc.Content.Split('\n').Select((text,i)=>(text,i)))if(terms.Any(t=>line.text.Contains(t,StringComparison.CurrentCultureIgnoreCase)))hits.Add($"{ch.Title} · {sc.Title} · {line.i+1}줄  {line.text.Trim()}");OccurrenceList.ItemsSource=hits;}
 void RefreshRelations(EntityCard c){RelationList.ItemsSource=_document.MindMap.Edges.Where(e=>e.From==c.Id||e.To==c.Id).Select(e=>{var id=e.From==c.Id?e.To:e.From;var other=_document.Cards.FirstOrDefault(x=>x.Id==id)?.Name??id;return $"{other} — {e.Label}";}).ToList();}
 void RenameProject_Click(object s,RoutedEventArgs e)=>RenameProject();
 void RenameProject(){if(ShowRenameDialog("소설 제목 변경",_document.Project.Title,out var title)){_document.Project.Title=title;_document.Project.UpdatedAt=DateTimeOffset.Now;RefreshAll();if(_scene!=null)ShowScene(_scene);}}
 bool ShowRenameDialog(string caption,string current,out string result){result=current;var dlg=new Window{Title=caption,Owner=this,WindowStartupLocation=WindowStartupLocation.CenterOwner,ResizeMode=ResizeMode.NoResize,SizeToContent=SizeToContent.WidthAndHeight,Background=(Brush)FindResource("Panel"),Foreground=(Brush)FindResource("Text")};var box=new TextBox{Text=current,MinWidth=320,Margin=new Thickness(16,16,16,10),Padding=new Thickness(8,6,8,6)};var ok=new Button{Content="확인",MinWidth=72,Margin=new Thickness(6,0,16,16),HorizontalAlignment=HorizontalAlignment.Right,IsDefault=true};var cancel=new Button{Content="취소",MinWidth=72,Margin=new Thickness(6,0,0,16),HorizontalAlignment=HorizontalAlignment.Right,IsCancel=true,Visibility=Visibility.Collapsed};var panel=new DockPanel();DockPanel.SetDock(ok,Dock.Bottom);panel.Children.Add(ok);panel.Children.Add(cancel);panel.Children.Add(box);dlg.Content=panel;dlg.SourceInitialized+=(_,_)=>ApplyWindowChromeTheme(dlg);string? accepted=null;ok.Click+=(_,_)=>{var value=box.Text.Trim();if(value.Length==0)return;accepted=value;dlg.DialogResult=true;};box.KeyDown+=(_,e)=>{if(e.Key==Key.Escape){dlg.DialogResult=false;e.Handled=true;}};dlg.Loaded+=(_,_)=>{box.Focus();box.SelectAll();};var acceptedDialog=dlg.ShowDialog()==true&&accepted!=null;if(acceptedDialog)result=accepted!;return acceptedDialog;}
 void NewProject_Click(object s,RoutedEventArgs e){_document=ProjectDocument.CreateSample();_path=null;_scene=null;_card=null;RefreshAll();SelectFirstScene();}
 async void OpenProject_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="TagWriter JSON (*.json)|*.json|JSON (*.json)|*.json"};if(d.ShowDialog()!=true)return;try{_document=await ProjectStore.LoadAsync(d.FileName);_path=d.FileName;_scene=null;_card=null;RefreshAll();SelectFirstScene();}catch(Exception ex){MessageBox.Show(ex.Message,"열기 실패");}}
 void SaveCommand_Executed(object s,ExecutedRoutedEventArgs e)=>SaveProject_Click(s,e);
 async void SaveProject_Click(object s,RoutedEventArgs e){PersistEditor();if(_path==null){var d=new SaveFileDialog{Filter="TagWriter JSON (*.json)|*.json",FileName=(string.IsNullOrWhiteSpace(_document.Project.Title)?"novel":_document.Project.Title)+".json"};if(d.ShowDialog()!=true)return;_path=d.FileName;}try{await ProjectStore.SaveAsync(_path,_document);UpdateStatus("저장됨");}catch(Exception ex){MessageBox.Show(ex.Message,"저장 실패");}}
 string NextChapterTitle(int n){var first=_document.Chapters.OrderBy(x=>x.Order).FirstOrDefault()?.Title??"";return first.StartsWith("Chapter ",StringComparison.OrdinalIgnoreCase)?$"Chapter {n}":$"{n}장";}
 void AddChapter_Click(object s,RoutedEventArgs e)=>AddChapter();
 void AddScene_Click(object s,RoutedEventArgs e){var ch=_document.Chapters.FirstOrDefault(x=>x.Scenes.Contains(_scene!))??_document.Chapters.LastOrDefault();if(ch!=null)AddSceneToChapter(ch);}
 void AddCard_Click(object s,RoutedEventArgs e){if(s is not MenuItem i||!Enum.TryParse<CardType>(i.Tag?.ToString(),out var t))return;var c=new EntityCard{Type=t,Name=$"새 {TypeName(t)}"};_document.Cards.Add(c);_document.MindMap.Nodes.Add(new MapNode{CardId=c.Id,X=80+(_document.MindMap.Nodes.Count%4)*190,Y=80+(_document.MindMap.Nodes.Count/4)*120});RefreshTree();ShowCard(c);}
 void SaveCard_Click(object s,RoutedEventArgs e){if(_card==null)return;_card.Description=CardDescription.Text;_card.Aliases=CardAliases.Text.Split(['\r','\n'],StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Trim()).Where(x=>x.Length>0).Distinct().ToList();_card.UpdatedAt=DateTimeOffset.Now;RefreshTree();RefreshOccurrences(_card);}
 void ShowAll_Click(object s,RoutedEventArgs e){SetActivityButton(ManuscriptModeButton);PersistEditor();_scene=null;_loading=true;var b=new StringBuilder();foreach(var c in _document.Chapters.OrderBy(x=>x.Order)){b.AppendLine(c.Title).AppendLine();foreach(var sc in c.Scenes.OrderBy(x=>x.Order))b.AppendLine(sc.Content).AppendLine();b.AppendLine("────────────────────────").AppendLine();}EditorTitle.Text="전체 원고";EditorSubtitle.Text="연속 읽기 · 읽기 전용";Editor.Text=b.ToString();Editor.IsReadOnly=true;_loading=false;EditorView.Visibility=Visibility.Visible;MindMapView.Visibility=Visibility.Collapsed;}
 void SetActivityButton(Button active){_activeActivityButton=active;foreach(var b in new[]{ProjectModeButton,ManuscriptModeButton,MindMapModeButton}){b.SetResourceReference(Control.BackgroundProperty,b==active?"Selection":"Surface");b.SetResourceReference(Control.ForegroundProperty,b==active?"Text":"Muted");}}
 void ProjectMode_Click(object s,RoutedEventArgs e){SetActivityButton(ProjectModeButton);EditorView.Visibility=Visibility.Visible;MindMapView.Visibility=Visibility.Collapsed;if(_scene==null)SelectFirstScene();else ShowScene(_scene);}
 void ManuscriptMode_Click(object s,RoutedEventArgs e){SetActivityButton(ManuscriptModeButton);EditorView.Visibility=Visibility.Visible;MindMapView.Visibility=Visibility.Collapsed;if(_scene==null)SelectFirstScene();else ShowScene(_scene);Editor.Focus();}
 void ShowMindMap_Click(object s,RoutedEventArgs e)=>ShowMindMap();
 void ShowMindMap(){SetActivityButton(MindMapModeButton);PersistEditor();Editor.IsReadOnly=false;EditorView.Visibility=Visibility.Collapsed;MindMapView.Visibility=Visibility.Visible;DrawMindMap();}
 void DrawMindMap(){MindCanvas.Children.Clear();foreach(var e in _document.MindMap.Edges){var a=_document.MindMap.Nodes.FirstOrDefault(n=>n.CardId==e.From);var b=_document.MindMap.Nodes.FirstOrDefault(n=>n.CardId==e.To);if(a==null||b==null)continue;MindCanvas.Children.Add(new Line{X1=a.X+65,Y1=a.Y+22,X2=b.X+65,Y2=b.Y+22,Stroke=(Brush)FindResource("Muted"),StrokeThickness=1.5});var l=new TextBlock{Text=e.Label,Foreground=(Brush)FindResource("Muted")};Canvas.SetLeft(l,(a.X+b.X)/2);Canvas.SetTop(l,(a.Y+b.Y)/2);MindCanvas.Children.Add(l);}foreach(var n in _document.MindMap.Nodes){var c=_document.Cards.FirstOrDefault(x=>x.Id==n.CardId);if(c==null)continue;var bt=new Button{Content=c.Name,Tag=c,MinWidth=130,Padding=new Thickness(10,6,10,6),Background=(Brush)FindResource("Panel2"),Foreground=(Brush)FindResource("Text")};bt.Click+=(_,_)=>ShowCard(c);Canvas.SetLeft(bt,n.X);Canvas.SetTop(bt,n.Y);MindCanvas.Children.Add(bt);}}
 void AddIdea_Click(object s,RoutedEventArgs e){_document.Ideas.Insert(0,new Idea{Text="새 아이디어"});RefreshIdeas();}
 void RefreshIdeas()=>IdeaList.ItemsSource=_document.Ideas.OrderByDescending(x=>x.CreatedAt).Select(x=>x.Done?$"✓ {x.Text}":x.Text).ToList();
 void UpdateStatus(string? p=null){PersistEditor();var chars=_document.Chapters.SelectMany(c=>c.Scenes).Sum(s=>s.Content.Length);var words=_document.Chapters.SelectMany(c=>c.Scenes).Sum(s=>s.Content.Split((char[]?)null,StringSplitOptions.RemoveEmptyEntries).Length);StatusText.Text=$"{(p==null?"":p+" · ")}{_document.Chapters.Count}장 · {chars:N0}자 · {words:N0}단어 · {_document.Cards.Count}카드";}
 void LeftPanelToggle_Click(object s,RoutedEventArgs e){if(!_leftCollapsed){_leftWidth=Math.Max(LeftPanelColumn.ActualWidth,210);LeftPanelColumn.MinWidth=0;LeftPanelColumn.Width=new GridLength(0);LeftSplitterColumn.Width=new GridLength(0);LeftSplitter.Visibility=Visibility.Collapsed;ProjectTree.Visibility=Visibility.Collapsed;LeftPanelLabel.Visibility=Visibility.Collapsed;LeftPanelToggle.Visibility=Visibility.Collapsed;LeftPanelCollapsedToggle.Visibility=Visibility.Visible;_leftCollapsed=true;}else{LeftPanelColumn.MinWidth=210;LeftPanelColumn.Width=new GridLength(Math.Max(_leftWidth,210));LeftSplitterColumn.Width=new GridLength(4);LeftSplitter.Visibility=Visibility.Visible;ProjectTree.Visibility=Visibility.Visible;LeftPanelLabel.Visibility=Visibility.Visible;LeftPanelLabel.Text="PROJECT";LeftPanelToggle.Visibility=Visibility.Visible;LeftPanelCollapsedToggle.Visibility=Visibility.Collapsed;_leftCollapsed=false;}}
 void RightPanelToggle_Click(object s,RoutedEventArgs e){if(!_rightCollapsed){_rightWidth=Math.Max(RightPanelColumn.ActualWidth,260);RightPanelColumn.MinWidth=0;RightPanelColumn.Width=new GridLength(0);RightSplitterColumn.Width=new GridLength(0);RightSplitter.Visibility=Visibility.Collapsed;ContextTabs.Visibility=Visibility.Collapsed;RightPanelLabel.Visibility=Visibility.Collapsed;RightPanelToggle.Visibility=Visibility.Collapsed;RightPanelCollapsedToggle.Visibility=Visibility.Visible;_rightCollapsed=true;}else{RightPanelColumn.MinWidth=260;RightPanelColumn.Width=new GridLength(Math.Max(_rightWidth,260));RightSplitterColumn.Width=new GridLength(4);RightSplitter.Visibility=Visibility.Visible;ContextTabs.Visibility=Visibility.Visible;RightPanelLabel.Visibility=Visibility.Visible;RightPanelLabel.Text="CONTEXT";RightPanelToggle.Visibility=Visibility.Visible;RightPanelCollapsedToggle.Visibility=Visibility.Collapsed;_rightCollapsed=false;}}
 void NormalMode_Click(object s,RoutedEventArgs e){SyncPaperToEditor();_paperMode=false;Editor.Visibility=Visibility.Visible;PaperInput.Visibility=Visibility.Collapsed;ManuscriptPaperScroll.Visibility=Visibility.Collapsed;PaperZoomControls.Visibility=Visibility.Collapsed;NormalTextControls.Visibility=Visibility.Visible;Editor.Focus();}
 void PaperMode_Click(object s,RoutedEventArgs e){PersistEditor();_paperMode=true;_loading=true;PaperInput.Text=Editor.Text;PaperInput.CaretIndex=Math.Min(Editor.CaretIndex,PaperInput.Text.Length);_loading=false;Editor.Visibility=Visibility.Collapsed;PaperInput.Visibility=Visibility.Visible;ManuscriptPaperScroll.Visibility=Visibility.Visible;PaperZoomControls.Visibility=Visibility.Visible;NormalTextControls.Visibility=Visibility.Collapsed;RenderManuscriptPaper();PaperInput.Focus();}
 void SyncPaperToEditor(){if(!_paperMode)return;_loading=true;Editor.Text=PaperInput.Text;if(_scene!=null)_scene.Content=PaperInput.Text;_loading=false;UpdateStatus();RefreshOccurrencesForScene();}
 void PaperInput_TextChanged(object s,TextChangedEventArgs e){if(_loading||!_paperMode)return;if(_scene!=null)_scene.Content=PaperInput.Text;SchedulePaperRender();UpdateStatus();RefreshOccurrencesForScene();}
 void SchedulePaperRender(){if(_paperRenderTimer==null){RenderManuscriptPaper();return;}_paperRenderTimer.Stop();_paperRenderTimer.Start();}
 void PaperInput_SelectionChanged(object s,RoutedEventArgs e){if(_paperMode)SchedulePaperRender();}
 void PaperInput_PreviewKeyDown(object s,KeyEventArgs e){if(!_paperMode||(e.Key!=Key.Up&&e.Key!=Key.Down)){if((Keyboard.Modifiers&ModifierKeys.Shift)==0)_paperKeyboardSelectionAnchor=null;return;}var text=PaperInput.Text??"";var shift=(Keyboard.Modifiers&ModifierKeys.Shift)!=0;var current=PaperInput.CaretIndex;if(shift){_paperKeyboardSelectionAnchor??=PaperInput.SelectionLength==0?current:(current<=PaperInput.SelectionStart?PaperInput.SelectionStart+PaperInput.SelectionLength:PaperInput.SelectionStart);if(PaperInput.SelectionLength>0){var start=PaperInput.SelectionStart;var end=start+PaperInput.SelectionLength;current=_paperKeyboardSelectionAnchor==start?end:start;}}else _paperKeyboardSelectionAnchor=null;var currentDisplay=PaperDisplayIndexFromTextIndex(text,current);var targetDisplay=Math.Max(0,currentDisplay+(e.Key==Key.Down?20:-20));var target=TextIndexFromPaperDisplayIndex(text,targetDisplay);if(shift){var anchor=_paperKeyboardSelectionAnchor!.Value;SetPaperSelection(anchor,target);}else PaperInput.Select(target,0);e.Handled=true;SchedulePaperRender();}
 void PaperZoomOut_Click(object s,RoutedEventArgs e)=>SetPaperZoom(_paperZoom-.1);
 void PaperZoomIn_Click(object s,RoutedEventArgs e)=>SetPaperZoom(_paperZoom+.1);
 void PaperZoom100_Click(object s,RoutedEventArgs e)=>SetPaperZoom(1);
 void SetPaperZoom(double value){_paperFit=false;_paperZoom=Math.Clamp(value,.35,2.5);RenderManuscriptPaper();}
 void PaperFit_Click(object s,RoutedEventArgs e){_paperFit=true;RenderManuscriptPaper();}
 void ManuscriptPaperScroll_SizeChanged(object s,SizeChangedEventArgs e){if(_paperMode&&_paperFit)RenderManuscriptPaper();}
 void ManuscriptPaperScroll_PreviewMouseWheel(object s,MouseWheelEventArgs e){if(!_paperMode)return;if((Keyboard.Modifiers&ModifierKeys.Control)!=0){SetPaperZoom(_paperZoom+(e.Delta>0?.1:-.1));e.Handled=true;return;}if((Keyboard.Modifiers&ModifierKeys.Shift)!=0){ManuscriptPaperScroll.ScrollToHorizontalOffset(ManuscriptPaperScroll.HorizontalOffset-(e.Delta/3.0));e.Handled=true;}}
 int PaperDisplayIndexFromTextIndex(string text,int textIndex){const int cols=20;var lineStart=0;var lineChars=0;for(int i=0;i<Math.Min(textIndex,text.Length);i++){var ch=text[i];if(ch=='\r')continue;if(ch=='\n'){var rows=Math.Max(1,(lineChars+cols-1)/cols);lineStart+=rows*cols;lineChars=0;}else lineChars++;}return lineStart+lineChars;}
 int TextIndexFromPaperDisplayIndex(string text,int displayIndex){var bestIndex=0;var bestDistance=int.MaxValue;for(int i=0;i<=text.Length;i++){var p=PaperDisplayIndexFromTextIndex(text,i);var d=Math.Abs(p-displayIndex);if(d<bestDistance||(d==bestDistance&&p<=displayIndex)){bestDistance=d;bestIndex=i;}if(p>displayIndex&&d>bestDistance)break;}return bestIndex;}
 char[] BuildPaperDisplay(string text,out int usedCells){const int cols=20;var placed=new Dictionary<int,char>();var lineStart=0;var lineChars=0;foreach(var ch in text){if(ch=='\r')continue;if(ch=='\n'){var rows=Math.Max(1,(lineChars+cols-1)/cols);lineStart+=rows*cols;lineChars=0;continue;}placed[lineStart+lineChars]=ch;lineChars++;}usedCells=Math.Max(lineStart+lineChars,1);var result=Enumerable.Repeat('\0',usedCells).ToArray();foreach(var kv in placed)if(kv.Key<result.Length)result[kv.Key]=kv.Value;return result;}
 void PaperSurface_MouseDown(ManuscriptPaperSurface surface,int displayIndex,MouseButtonEventArgs e){var textIndex=TextIndexFromPaperDisplayIndex(PaperInput.Text,displayIndex);_paperDragging=true;_paperDragAnchorText=textIndex;ManuscriptPaperScroll.CaptureMouse();if((Keyboard.Modifiers&ModifierKeys.Shift)!=0){var anchor=PaperInput.SelectionLength>0?PaperInput.SelectionStart:PaperInput.CaretIndex;SetPaperSelection(anchor,textIndex);}else{PaperInput.Select(textIndex,0);_paperDragAnchorText=textIndex;}PaperInput.Focus();UpdatePaperSurfaceStates();}
 void PaperSurface_MouseMove(ManuscriptPaperSurface surface,int displayIndex,MouseEventArgs e){if(!_paperDragging)return;var textIndex=TextIndexFromPaperDisplayIndex(PaperInput.Text,displayIndex);SetPaperSelection(_paperDragAnchorText,textIndex);UpdatePaperSurfaceStates();}
 void PaperSurface_MouseUp(ManuscriptPaperSurface surface,MouseButtonEventArgs e){_paperDragging=false;PaperInput.Focus();}
 void ManuscriptPaperScroll_PreviewMouseMove(object s,MouseEventArgs e){if(!_paperDragging||e.LeftButton!=MouseButtonState.Pressed)return;var p=e.GetPosition(ManuscriptPaperScroll);const double edge=48;if(p.Y<edge)ManuscriptPaperScroll.ScrollToVerticalOffset(Math.Max(0,ManuscriptPaperScroll.VerticalOffset-22));else if(p.Y>ManuscriptPaperScroll.ViewportHeight-edge)ManuscriptPaperScroll.ScrollToVerticalOffset(ManuscriptPaperScroll.VerticalOffset+22);var bestCell=-1;var bestDistance=double.MaxValue;foreach(var surface in _paperSurfaces){var q=e.GetPosition(surface);var col=(int)Math.Floor((q.X/_paperZoom-PaperMargin)/PaperCell);var row=(int)Math.Floor((q.Y/_paperZoom-PaperMargin)/PaperCell);if(col>=0&&col<20&&row>=0&&row<10){bestCell=surface.PageIndex*200+row*20+col;break;}var clampedX=Math.Clamp(q.X,PaperMargin*_paperZoom,(PaperMargin+20*PaperCell)*_paperZoom-1);var clampedY=Math.Clamp(q.Y,PaperMargin*_paperZoom,(PaperMargin+10*PaperCell)*_paperZoom-1);var dx=q.X-clampedX;var dy=q.Y-clampedY;var d=dx*dx+dy*dy;if(d<bestDistance){bestDistance=d;col=Math.Clamp((int)((clampedX/_paperZoom-PaperMargin)/PaperCell),0,19);row=Math.Clamp((int)((clampedY/_paperZoom-PaperMargin)/PaperCell),0,9);bestCell=surface.PageIndex*200+row*20+col;}}if(bestCell>=0){var textIndex=TextIndexFromPaperDisplayIndex(PaperInput.Text,bestCell);SetPaperSelection(_paperDragAnchorText,textIndex);UpdatePaperSurfaceStates();}e.Handled=true;}
 void ManuscriptPaperScroll_PreviewMouseLeftButtonUp(object s,MouseButtonEventArgs e){if(!_paperDragging)return;_paperDragging=false;if(ManuscriptPaperScroll.IsMouseCaptured)ManuscriptPaperScroll.ReleaseMouseCapture();PaperInput.Focus();e.Handled=true;}
 void SetPaperSelection(int anchor,int current){var start=Math.Min(anchor,current);var length=Math.Abs(current-anchor);PaperInput.Select(start,length);}
 void EnsurePaperSurfaceCount(int pages,double logicalW,double logicalH){while(_paperSurfaces.Count<pages){var surface=new ManuscriptPaperSurface();surface.CellMouseDown+=PaperSurface_MouseDown;surface.CellMouseMove+=PaperSurface_MouseMove;surface.CellMouseUp+=PaperSurface_MouseUp;_paperSurfaces.Add(surface);ManuscriptPaperHost.Children.Add(surface);}while(_paperSurfaces.Count>pages){var last=_paperSurfaces[^1];ManuscriptPaperHost.Children.Remove(last);_paperSurfaces.RemoveAt(_paperSurfaces.Count-1);}for(int p=0;p<pages;p++){var s=_paperSurfaces[p];s.PageIndex=p;s.Zoom=_paperZoom;s.CellSize=PaperCell;s.PaperMargin=PaperMargin;s.Width=logicalW*_paperZoom;s.Height=logicalH*_paperZoom;s.Margin=new Thickness(0,0,0,22);s.PaperBrush=(Brush)FindResource("Panel2");s.GridBrush=(Brush)FindResource("Border");s.TextBrush=(Brush)FindResource("Text");s.CaretBrush=(Brush)FindResource("Selection");s.SelectionBrush=(Brush)FindResource("Selection");s.HoverBrush=(Brush)FindResource("Accent");s.PageNumberBrush=(Brush)FindResource("Muted");}}
 void UpdatePaperSurfaceStates(){var text=PaperInput.Text??"";var caret=PaperDisplayIndexFromTextIndex(text,PaperInput.CaretIndex);var selStart=PaperDisplayIndexFromTextIndex(text,PaperInput.SelectionStart);var selEnd=PaperDisplayIndexFromTextIndex(text,PaperInput.SelectionStart+PaperInput.SelectionLength);foreach(var s in _paperSurfaces){s.CaretCell=PaperInput.SelectionLength==0?caret:-1;s.SelectionStartCell=PaperInput.SelectionLength>0?Math.Min(selStart,selEnd):-1;s.SelectionEndCell=PaperInput.SelectionLength>0?Math.Max(selStart,selEnd):-1;s.InvalidateVisual();}}
 void EnsureCaretVisible(){if(_paperSurfaces.Count==0)return;var cell=PaperDisplayIndexFromTextIndex(PaperInput.Text,PaperInput.CaretIndex);var page=Math.Clamp(cell/200,0,_paperSurfaces.Count-1);_paperSurfaces[page].BringIntoView();}
 void RenderManuscriptPaper(){if(!_paperMode)return;var text=PaperInput.Text??"";var chars=BuildPaperDisplay(text,out var usedCells);const int perPage=200,cols=20,rows=10;var caretDisplay=PaperDisplayIndexFromTextIndex(text,PaperInput.CaretIndex);var pages=Math.Max(1,(int)Math.Ceiling(Math.Max(usedCells,caretDisplay+1)/(double)perPage));var logicalW=cols*PaperCell+PaperMargin*2;var logicalH=rows*PaperCell+PaperMargin*2;if(_paperFit&&ManuscriptPaperScroll.ViewportWidth>100)_paperZoom=Math.Clamp((ManuscriptPaperScroll.ViewportWidth-72)/logicalW,.35,1.6);PaperZoomText.Text=$"{_paperZoom*100:0}%";PaperPageText.Text=$"{pages}매 · 20×10";EnsurePaperSurfaceCount(pages,logicalW,logicalH);for(int p=0;p<pages;p++){var pageCells=new char[perPage];var from=p*perPage;var count=Math.Max(0,Math.Min(perPage,chars.Length-from));if(count>0)Array.Copy(chars,from,pageCells,0,count);_paperSurfaces[p].Cells=pageCells;}_document.Project.UpdatedAt=DateTimeOffset.Now;UpdatePaperSurfaceStates();EnsureCaretVisible();}
 void ThemeToggle_Click(object s,RoutedEventArgs e)=>ApplyTheme(!_dark);
 void ApplyTheme(bool dark){
  _dark=dark;
  SetBrush("Bg",dark?"#181B1F":"#E8EBEF"); SetBrush("Surface",dark?"#20242A":"#F5F6F8");
  SetBrush("Panel",dark?"#242930":"#EEF1F4"); SetBrush("Panel2",dark?"#2B3139":"#FFFFFF");
  SetBrush("EditorBg",dark?"#1D2126":"#FFFFFF"); SetBrush("Text",dark?"#E6E9ED":"#20242A");
  SetBrush("Muted",dark?"#939BA6":"#66707C"); SetBrush("Border",dark?"#343B45":"#D4D9E0");
  SetBrush("Accent",dark?"#70A9E8":"#2F72B7"); SetBrush("Selection",dark?"#304B68":"#BFD9F4"); SetBrush("Hover",dark?"#2B3139":"#E1E5EA"); SetBrush("ToolTipBg",dark?"#242930":"#FFFFFF"); SetBrush("ToolTipText",dark?"#E6E9ED":"#20242A"); SetBrush("TabSelected",dark?"#1E2227":"#E1E5EA");
  ThemeGlyph.Text=dark?"☾ Dark":"☀ Light"; ThemeGlyph.Foreground=(Brush)FindResource("Text"); ThemeToggle.Foreground=(Brush)FindResource("Text"); ThemeToggle.Background=(Brush)FindResource("Panel2"); ThemeToggle.IsChecked=!dark; _document.Settings.Theme=dark?"dark":"light"; if(_activeActivityButton!=null)SetActivityButton(_activeActivityButton); ApplyWindowChromeTheme();
 }
 void ApplyWindowChromeTheme()=>ApplyWindowChromeTheme(this);
 void ApplyWindowChromeTheme(Window window){try{var hwnd=new WindowInteropHelper(window).Handle;if(hwnd==IntPtr.Zero)return;int value=_dark?1:0;DwmSetWindowAttribute(hwnd,20,ref value,sizeof(int));}catch{}}
 [DllImport("dwmapi.dll")] static extern int DwmSetWindowAttribute(IntPtr hwnd,int attribute,ref int value,int size);
 void SetBrush(string key,string hex)=>Application.Current.Resources[key]=new SolidColorBrush((Color)ColorConverter.ConvertFromString(hex));
}
