using Microsoft.Win32; using System.Windows.Input; using System.Runtime.InteropServices; using System.Text; using System.Windows; using System.Windows.Controls; using System.Windows.Interop; using System.Windows.Media; using System.Windows.Shapes; using TagWriter.Models; using TagWriter.Services;
namespace TagWriter;
public partial class MainWindow:Window {
 ProjectDocument _document=ProjectDocument.CreateSample(); string? _path; Scene? _scene; EntityCard? _card; bool _loading; bool _dark=true; bool _leftCollapsed=false,_rightCollapsed=false; double _leftWidth=250,_rightWidth=310; bool _paperMode=false,_paperFit=true; double _paperZoom=1.0; const double PaperCell=34,PaperMargin=42;
 public MainWindow(){InitializeComponent();SourceInitialized+=(_,_)=>ApplyWindowChromeTheme();Loaded+=(_,_)=>InitializeEditorPreferences();RefreshAll();SelectFirstScene();ApplyTheme(_document.Settings.Theme!="light");}
 void InitializeEditorPreferences(){FontFamilyBox.ItemsSource=Fonts.SystemFontFamilies.OrderBy(f=>f.Source).ToList();FontFamilyBox.SelectedItem=Fonts.SystemFontFamilies.FirstOrDefault(f=>f.Source==_document.Settings.EditorFontFamily)??new FontFamily(_document.Settings.EditorFontFamily);FontSizeBox.ItemsSource=new double[]{12,13,14,15,16,17,18,20,22,24};FontSizeBox.Text=_document.Settings.EditorFontSize.ToString("0.#");ApplyEditorPreferences();}
 void ApplyEditorPreferences(){try{Editor.FontFamily=new FontFamily(_document.Settings.EditorFontFamily);}catch{Editor.FontFamily=new FontFamily("Malgun Gothic");}Editor.FontSize=Math.Clamp(_document.Settings.EditorFontSize,9,48);Editor.SetValue(TextBlock.LineHeightProperty,Math.Max(Editor.FontSize*1.7,Editor.FontSize+6));}
 void FontFamilyBox_SelectionChanged(object s,SelectionChangedEventArgs e){if(FontFamilyBox.SelectedItem is FontFamily f){_document.Settings.EditorFontFamily=f.Source;ApplyEditorPreferences();}}
 void FontSizeBox_SelectionChanged(object s,SelectionChangedEventArgs e)=>ApplyFontSizeBox();
 void FontSizeBox_LostKeyboardFocus(object s,KeyboardFocusChangedEventArgs e)=>ApplyFontSizeBox();
 void ApplyFontSizeBox(){if(double.TryParse(FontSizeBox.Text,out var size)){_document.Settings.EditorFontSize=Math.Clamp(size,9,48);ApplyEditorPreferences();}}
 void RefreshAll(){RefreshTree();RefreshIdeas();UpdateStatus();Title=$"{_document.Project.Title} — TagWriter";}
 void RefreshTree(){
  ProjectTree.Items.Clear(); var manuscript=new TreeViewItem{Header=_document.Project.Title,IsExpanded=true,Tag="manuscript"};
  foreach(var chapter in _document.Chapters.OrderBy(x=>x.Order)){var cn=new TreeViewItem{Header=chapter.Title,IsExpanded=true,Tag=chapter};foreach(var scene in chapter.Scenes.OrderBy(x=>x.Order))cn.Items.Add(new TreeViewItem{Header=scene.Title,Tag=scene});manuscript.Items.Add(cn);} ProjectTree.Items.Add(manuscript);
  var cards=new TreeViewItem{Header="설정 카드",IsExpanded=true}; foreach(CardType type in Enum.GetValues<CardType>()){var g=new TreeViewItem{Header=TypeName(type),IsExpanded=true};foreach(var card in _document.Cards.Where(x=>x.Type==type).OrderBy(x=>x.Name))g.Items.Add(new TreeViewItem{Header=card.Name,Tag=card});cards.Items.Add(g);} ProjectTree.Items.Add(cards);ProjectTree.Items.Add(new TreeViewItem{Header="◇ 마인드맵",Tag="mindmap"});
 }
 static string TypeName(CardType t)=>t switch{CardType.Character=>"캐릭터",CardType.Location=>"장소",CardType.Item=>"물건",CardType.Event=>"사건",_=>t.ToString()};
 void SelectFirstScene(){var s=_document.Chapters.OrderBy(x=>x.Order).SelectMany(x=>x.Scenes.OrderBy(y=>y.Order)).FirstOrDefault();if(s!=null)ShowScene(s);}
 void ProjectTree_MouseDoubleClick(object s,System.Windows.Input.MouseButtonEventArgs e){if(ProjectTree.SelectedItem is not TreeViewItem i)return;if(i.Tag as string=="manuscript"){RenameProject();e.Handled=true;}else if(i.Tag is Chapter chapter){RenameChapter(chapter);e.Handled=true;}}
 void RenameChapter(Chapter chapter){var dlg=new Window{Title="장 제목 변경",Owner=this,WindowStartupLocation=WindowStartupLocation.CenterOwner,ResizeMode=ResizeMode.NoResize,SizeToContent=SizeToContent.WidthAndHeight,Background=(Brush)FindResource("Panel"),Foreground=(Brush)FindResource("Text")};var box=new TextBox{Text=chapter.Title,MinWidth=320,Margin=new Thickness(16,16,16,10),Padding=new Thickness(8,6,8,6)};var ok=new Button{Content="확인",MinWidth=72,Margin=new Thickness(6,0,16,16),HorizontalAlignment=HorizontalAlignment.Right};var panel=new DockPanel();DockPanel.SetDock(ok,Dock.Bottom);panel.Children.Add(ok);panel.Children.Add(box);dlg.Content=panel;ok.Click+=(_,_)=>{var title=box.Text.Trim();if(title.Length==0)return;chapter.Title=title;_document.Project.UpdatedAt=DateTimeOffset.Now;dlg.DialogResult=true;};box.SelectAll();box.Focus();if(dlg.ShowDialog()==true){RefreshTree();if(_scene!=null)ShowScene(_scene);}}
 void ProjectTree_SelectedItemChanged(object s,RoutedPropertyChangedEventArgs<object> e){if(e.NewValue is not TreeViewItem i)return;if(i.Tag is Scene sc)ShowScene(sc);else if(i.Tag is EntityCard c)ShowCard(c);else if(i.Tag as string=="mindmap")ShowMindMap();}
 void ShowScene(Scene s){PersistEditor();_scene=s;_card=null;_loading=true;Editor.IsReadOnly=false;Editor.Text=s.Content;PaperInput.Text=s.Content;var ch=_document.Chapters.FirstOrDefault(x=>x.Scenes.Contains(s));EditorTitle.Text=$"{_document.Project.Title}  |  {ch?.Title??""}  |  {s.Title}";EditorSubtitle.Text="원고 편집";_loading=false;EditorView.Visibility=Visibility.Visible;MindMapView.Visibility=Visibility.Collapsed;RefreshOccurrencesForScene();UpdateStatus();}
 void ShowCard(EntityCard c){_card=c;CardName.Text=c.Name;CardTypeText.Text=TypeName(c.Type);CardDescription.Text=c.Description;CardAliases.Text=string.Join(Environment.NewLine,c.Aliases);RefreshOccurrences(c);RefreshRelations(c);}
 void PersistEditor(){if(_scene!=null&&!_loading)_scene.Content=Editor.Text;}
 void Editor_TextChanged(object s,TextChangedEventArgs e){if(_loading||_scene==null)return;_scene.Content=Editor.Text;UpdateStatus();RefreshOccurrencesForScene();}
 void RefreshOccurrencesForScene(){if(_scene==null)return;OccurrenceList.ItemsSource=_document.Cards.Where(c=>c.Aliases.Append(c.Name).Any(a=>!string.IsNullOrWhiteSpace(a)&&_scene.Content.Contains(a,StringComparison.CurrentCultureIgnoreCase))).Select(c=>$"#{c.Name} · 현재 장면에서 발견").ToList();}
 void RefreshOccurrences(EntityCard c){var terms=c.Aliases.Append(c.Name).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct().ToArray();var hits=new List<string>();foreach(var ch in _document.Chapters.OrderBy(x=>x.Order))foreach(var sc in ch.Scenes.OrderBy(x=>x.Order))foreach(var line in sc.Content.Split('\n').Select((text,i)=>(text,i)))if(terms.Any(t=>line.text.Contains(t,StringComparison.CurrentCultureIgnoreCase)))hits.Add($"{ch.Title} · {sc.Title} · {line.i+1}줄  {line.text.Trim()}");OccurrenceList.ItemsSource=hits;}
 void RefreshRelations(EntityCard c){RelationList.ItemsSource=_document.MindMap.Edges.Where(e=>e.From==c.Id||e.To==c.Id).Select(e=>{var id=e.From==c.Id?e.To:e.From;var other=_document.Cards.FirstOrDefault(x=>x.Id==id)?.Name??id;return $"{other} — {e.Label}";}).ToList();}
 void RenameProject_Click(object s,RoutedEventArgs e)=>RenameProject();
 void RenameProject(){var dlg=new Window{Title="소설 제목 변경",Owner=this,WindowStartupLocation=WindowStartupLocation.CenterOwner,ResizeMode=ResizeMode.NoResize,SizeToContent=SizeToContent.WidthAndHeight,Background=(Brush)FindResource("Panel"),Foreground=(Brush)FindResource("Text")};var box=new TextBox{Text=_document.Project.Title,MinWidth=320,Margin=new Thickness(16,16,16,10),Padding=new Thickness(8,6,8,6)};var ok=new Button{Content="확인",MinWidth=72,Margin=new Thickness(6,0,16,16),HorizontalAlignment=HorizontalAlignment.Right};var panel=new DockPanel();DockPanel.SetDock(ok,Dock.Bottom);panel.Children.Add(ok);panel.Children.Add(box);dlg.Content=panel;ok.Click+=(_,_)=>{var title=box.Text.Trim();if(title.Length==0)return;_document.Project.Title=title;_document.Project.UpdatedAt=DateTimeOffset.Now;dlg.DialogResult=true;};box.SelectAll();box.Focus();if(dlg.ShowDialog()==true){RefreshAll();if(_scene!=null)ShowScene(_scene);}}
 void NewProject_Click(object s,RoutedEventArgs e){_document=ProjectDocument.CreateSample();_path=null;_scene=null;_card=null;RefreshAll();SelectFirstScene();}
 async void OpenProject_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="TagWriter JSON (*.json)|*.json|JSON (*.json)|*.json"};if(d.ShowDialog()!=true)return;try{_document=await ProjectStore.LoadAsync(d.FileName);_path=d.FileName;_scene=null;_card=null;RefreshAll();SelectFirstScene();}catch(Exception ex){MessageBox.Show(ex.Message,"열기 실패");}}
 async void SaveProject_Click(object s,RoutedEventArgs e){PersistEditor();if(_path==null){var d=new SaveFileDialog{Filter="TagWriter JSON (*.json)|*.json",FileName=(string.IsNullOrWhiteSpace(_document.Project.Title)?"novel":_document.Project.Title)+".json"};if(d.ShowDialog()!=true)return;_path=d.FileName;}try{await ProjectStore.SaveAsync(_path,_document);UpdateStatus("저장됨");}catch(Exception ex){MessageBox.Show(ex.Message,"저장 실패");}}
 string NextChapterTitle(int n){var first=_document.Chapters.OrderBy(x=>x.Order).FirstOrDefault()?.Title??"";return first.StartsWith("Chapter ",StringComparison.OrdinalIgnoreCase)?$"Chapter {n}":$"{n}장";}
 void AddChapter_Click(object s,RoutedEventArgs e){PersistEditor();var n=_document.Chapters.Count+1;var c=new Chapter{Title=NextChapterTitle(n),Order=n};c.Scenes.Add(new Scene{Title="Scene 1",Order=1});_document.Chapters.Add(c);RefreshTree();ShowScene(c.Scenes[0]);}
 void AddScene_Click(object s,RoutedEventArgs e){var c=_document.Chapters.FirstOrDefault(x=>x.Scenes.Contains(_scene!))??_document.Chapters.LastOrDefault();if(c==null)return;var sc=new Scene{Title=$"Scene {c.Scenes.Count+1}",Order=c.Scenes.Count+1};c.Scenes.Add(sc);RefreshTree();ShowScene(sc);}
 void AddCard_Click(object s,RoutedEventArgs e){if(s is not MenuItem i||!Enum.TryParse<CardType>(i.Tag?.ToString(),out var t))return;var c=new EntityCard{Type=t,Name=$"새 {TypeName(t)}"};_document.Cards.Add(c);_document.MindMap.Nodes.Add(new MapNode{CardId=c.Id,X=80+(_document.MindMap.Nodes.Count%4)*190,Y=80+(_document.MindMap.Nodes.Count/4)*120});RefreshTree();ShowCard(c);}
 void SaveCard_Click(object s,RoutedEventArgs e){if(_card==null)return;_card.Description=CardDescription.Text;_card.Aliases=CardAliases.Text.Split(['\r','\n'],StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Trim()).Where(x=>x.Length>0).Distinct().ToList();_card.UpdatedAt=DateTimeOffset.Now;RefreshTree();RefreshOccurrences(_card);}
 void ShowAll_Click(object s,RoutedEventArgs e){PersistEditor();_scene=null;_loading=true;var b=new StringBuilder();foreach(var c in _document.Chapters.OrderBy(x=>x.Order)){b.AppendLine(c.Title).AppendLine();foreach(var sc in c.Scenes.OrderBy(x=>x.Order))b.AppendLine(sc.Content).AppendLine();b.AppendLine("────────────────────────").AppendLine();}EditorTitle.Text="전체 원고";EditorSubtitle.Text="연속 읽기 · 읽기 전용";Editor.Text=b.ToString();Editor.IsReadOnly=true;_loading=false;EditorView.Visibility=Visibility.Visible;MindMapView.Visibility=Visibility.Collapsed;}
 void SetActivityButton(Button active){foreach(var b in new[]{ProjectModeButton,ManuscriptModeButton,MindMapModeButton}){b.Background=(Brush)FindResource(b==active?"Selection":"Surface");b.Foreground=(Brush)FindResource(b==active?"Text":"Muted");}}
 void ProjectMode_Click(object s,RoutedEventArgs e){SetActivityButton(ProjectModeButton);EditorView.Visibility=Visibility.Visible;MindMapView.Visibility=Visibility.Collapsed;if(_scene==null)SelectFirstScene();else ShowScene(_scene);}
 void ManuscriptMode_Click(object s,RoutedEventArgs e){SetActivityButton(ManuscriptModeButton);EditorView.Visibility=Visibility.Visible;MindMapView.Visibility=Visibility.Collapsed;if(_scene==null)SelectFirstScene();else ShowScene(_scene);Editor.Focus();}
 void ShowMindMap_Click(object s,RoutedEventArgs e)=>ShowMindMap();
 void ShowMindMap(){SetActivityButton(MindMapModeButton);PersistEditor();Editor.IsReadOnly=false;EditorView.Visibility=Visibility.Collapsed;MindMapView.Visibility=Visibility.Visible;DrawMindMap();}
 void DrawMindMap(){MindCanvas.Children.Clear();foreach(var e in _document.MindMap.Edges){var a=_document.MindMap.Nodes.FirstOrDefault(n=>n.CardId==e.From);var b=_document.MindMap.Nodes.FirstOrDefault(n=>n.CardId==e.To);if(a==null||b==null)continue;MindCanvas.Children.Add(new Line{X1=a.X+65,Y1=a.Y+22,X2=b.X+65,Y2=b.Y+22,Stroke=(Brush)FindResource("Muted"),StrokeThickness=1.5});var l=new TextBlock{Text=e.Label,Foreground=(Brush)FindResource("Muted")};Canvas.SetLeft(l,(a.X+b.X)/2);Canvas.SetTop(l,(a.Y+b.Y)/2);MindCanvas.Children.Add(l);}foreach(var n in _document.MindMap.Nodes){var c=_document.Cards.FirstOrDefault(x=>x.Id==n.CardId);if(c==null)continue;var bt=new Button{Content=c.Name,Tag=c,MinWidth=130,Padding=new Thickness(10,6,10,6),Background=(Brush)FindResource("Panel2"),Foreground=(Brush)FindResource("Text")};bt.Click+=(_,_)=>ShowCard(c);Canvas.SetLeft(bt,n.X);Canvas.SetTop(bt,n.Y);MindCanvas.Children.Add(bt);}}
 void AddIdea_Click(object s,RoutedEventArgs e){_document.Ideas.Insert(0,new Idea{Text="새 아이디어"});RefreshIdeas();}
 void RefreshIdeas()=>IdeaList.ItemsSource=_document.Ideas.OrderByDescending(x=>x.CreatedAt).Select(x=>x.Done?$"✓ {x.Text}":x.Text).ToList();
 void UpdateStatus(string? p=null){PersistEditor();var chars=_document.Chapters.SelectMany(c=>c.Scenes).Sum(s=>s.Content.Length);var words=_document.Chapters.SelectMany(c=>c.Scenes).Sum(s=>s.Content.Split((char[]?)null,StringSplitOptions.RemoveEmptyEntries).Length);StatusText.Text=$"{(p==null?"":p+" · ")}{_document.Chapters.Count}장 · {chars:N0}자 · {words:N0}단어 · {_document.Cards.Count}카드";}
 void LeftPanelToggle_Click(object s,RoutedEventArgs e){if(!_leftCollapsed){_leftWidth=Math.Max(LeftPanelColumn.ActualWidth,210);LeftPanelColumn.MinWidth=0;LeftPanelColumn.Width=new GridLength(36);LeftSplitterColumn.Width=new GridLength(0);LeftSplitter.Visibility=Visibility.Collapsed;ProjectTree.Visibility=Visibility.Collapsed;LeftPanelLabel.Visibility=Visibility.Collapsed;LeftPanelToggle.Content=">";_leftCollapsed=true;}else{LeftPanelColumn.MinWidth=210;LeftPanelColumn.Width=new GridLength(Math.Max(_leftWidth,210));LeftSplitterColumn.Width=new GridLength(4);LeftSplitter.Visibility=Visibility.Visible;ProjectTree.Visibility=Visibility.Visible;LeftPanelLabel.Visibility=Visibility.Visible;LeftPanelLabel.Text="PROJECT";LeftPanelToggle.Content="<";_leftCollapsed=false;}}
 void RightPanelToggle_Click(object s,RoutedEventArgs e){if(!_rightCollapsed){_rightWidth=Math.Max(RightPanelColumn.ActualWidth,260);RightPanelColumn.MinWidth=0;RightPanelColumn.Width=new GridLength(36);RightSplitterColumn.Width=new GridLength(0);RightSplitter.Visibility=Visibility.Collapsed;ContextTabs.Visibility=Visibility.Collapsed;RightPanelLabel.Visibility=Visibility.Collapsed;RightPanelToggle.Content="<";_rightCollapsed=true;}else{RightPanelColumn.MinWidth=260;RightPanelColumn.Width=new GridLength(Math.Max(_rightWidth,260));RightSplitterColumn.Width=new GridLength(4);RightSplitter.Visibility=Visibility.Visible;ContextTabs.Visibility=Visibility.Visible;RightPanelLabel.Visibility=Visibility.Visible;RightPanelLabel.Text="CONTEXT";RightPanelToggle.Content=">";_rightCollapsed=false;}}
 void NormalMode_Click(object s,RoutedEventArgs e){SyncPaperToEditor();_paperMode=false;Editor.Visibility=Visibility.Visible;PaperInput.Visibility=Visibility.Collapsed;ManuscriptPaperScroll.Visibility=Visibility.Collapsed;PaperZoomControls.Visibility=Visibility.Collapsed;NormalTextControls.Visibility=Visibility.Visible;Editor.Focus();}
 void PaperMode_Click(object s,RoutedEventArgs e){PersistEditor();_paperMode=true;_loading=true;PaperInput.Text=Editor.Text;PaperInput.CaretIndex=Math.Min(Editor.CaretIndex,PaperInput.Text.Length);_loading=false;Editor.Visibility=Visibility.Collapsed;PaperInput.Visibility=Visibility.Visible;ManuscriptPaperScroll.Visibility=Visibility.Visible;PaperZoomControls.Visibility=Visibility.Visible;NormalTextControls.Visibility=Visibility.Collapsed;RenderManuscriptPaper();PaperInput.Focus();}
 void SyncPaperToEditor(){if(!_paperMode)return;_loading=true;Editor.Text=PaperInput.Text;if(_scene!=null)_scene.Content=PaperInput.Text;_loading=false;UpdateStatus();RefreshOccurrencesForScene();}
 void PaperInput_TextChanged(object s,TextChangedEventArgs e){if(_loading||!_paperMode)return;if(_scene!=null)_scene.Content=PaperInput.Text;RenderManuscriptPaper();UpdateStatus();RefreshOccurrencesForScene();}
 void PaperInput_SelectionChanged(object s,RoutedEventArgs e){if(_paperMode)RenderManuscriptPaper();}
 void PaperZoomOut_Click(object s,RoutedEventArgs e)=>SetPaperZoom(_paperZoom-.1);
 void PaperZoomIn_Click(object s,RoutedEventArgs e)=>SetPaperZoom(_paperZoom+.1);
 void PaperZoom100_Click(object s,RoutedEventArgs e)=>SetPaperZoom(1);
 void SetPaperZoom(double value){_paperFit=false;_paperZoom=Math.Clamp(value,.35,2.5);RenderManuscriptPaper();}
 void PaperFit_Click(object s,RoutedEventArgs e){_paperFit=true;RenderManuscriptPaper();}
 void ManuscriptPaperScroll_SizeChanged(object s,SizeChangedEventArgs e){if(_paperMode&&_paperFit)RenderManuscriptPaper();}
 void ManuscriptPaperScroll_PreviewMouseWheel(object s,MouseWheelEventArgs e){if(!_paperMode)return;if((Keyboard.Modifiers&ModifierKeys.Control)!=0){SetPaperZoom(_paperZoom+(e.Delta>0?.1:-.1));e.Handled=true;return;}if((Keyboard.Modifiers&ModifierKeys.Shift)!=0){ManuscriptPaperScroll.ScrollToHorizontalOffset(ManuscriptPaperScroll.HorizontalOffset-(e.Delta/3.0));e.Handled=true;}}
 int PaperDisplayIndexFromTextIndex(string text,int textIndex){var n=0;for(int i=0;i<Math.Min(textIndex,text.Length);i++)if(text[i]!='\r')n++;return n;}
 int TextIndexFromPaperDisplayIndex(string text,int displayIndex){var n=0;for(int i=0;i<text.Length;i++){if(text[i]=='\r')continue;if(n>=displayIndex)return i;n++;}return text.Length;}
 void PaperCanvas_MouseLeftButtonDown(object s,MouseButtonEventArgs e){if(s is not Canvas canvas||canvas.Tag is not int page)return;var pt=e.GetPosition(canvas);var col=(int)((pt.X/_paperZoom-PaperMargin)/PaperCell);var row=(int)((pt.Y/_paperZoom-PaperMargin)/PaperCell);col=Math.Clamp(col,0,19);row=Math.Clamp(row,0,9);var displayIndex=page*200+row*20+col;PaperInput.CaretIndex=TextIndexFromPaperDisplayIndex(PaperInput.Text,displayIndex);PaperInput.Focus();e.Handled=true;RenderManuscriptPaper();}
 void RenderManuscriptPaper(){if(!_paperMode)return;var text=PaperInput.Text??"";var display=text.Replace("\r","").Replace("\n","　");var chars=display.ToCharArray();const int perPage=200,cols=20,rows=10;var caretDisplay=PaperDisplayIndexFromTextIndex(text,PaperInput.CaretIndex);var pages=Math.Max(1,(int)Math.Ceiling(Math.Max(chars.Length,caretDisplay+1)/(double)perPage));var logicalW=cols*PaperCell+PaperMargin*2;var logicalH=rows*PaperCell+PaperMargin*2;if(_paperFit&&ManuscriptPaperScroll.ViewportWidth>100)_paperZoom=Math.Clamp((ManuscriptPaperScroll.ViewportWidth-72)/logicalW,.35,1.6);PaperZoomText.Text=$"{_paperZoom*100:0}%";PaperPageText.Text=$"{pages}매 · 20×10";ManuscriptPaperHost.Children.Clear();for(int p=0;p<pages;p++){var canvas=new Canvas{Tag=p,Width=logicalW*_paperZoom,Height=logicalH*_paperZoom,Background=(Brush)FindResource("Panel2"),Margin=new Thickness(0,0,0,22),Focusable=true};canvas.MouseLeftButtonDown+=PaperCanvas_MouseLeftButtonDown;for(int r=0;r<=rows;r++){var y=(PaperMargin+r*PaperCell)*_paperZoom;canvas.Children.Add(new Line{X1=PaperMargin*_paperZoom,Y1=y,X2=(PaperMargin+cols*PaperCell)*_paperZoom,Y2=y,Stroke=(Brush)FindResource("Border"),StrokeThickness=1});}for(int col=0;col<=cols;col++){var xx=(PaperMargin+col*PaperCell)*_paperZoom;canvas.Children.Add(new Line{X1=xx,Y1=PaperMargin*_paperZoom,X2=xx,Y2=(PaperMargin+rows*PaperCell)*_paperZoom,Stroke=(Brush)FindResource("Border"),StrokeThickness=1});}if(caretDisplay/200==p){var ci=caretDisplay%200;var caret=new Rectangle{Width=PaperCell*_paperZoom,Height=PaperCell*_paperZoom,Fill=(Brush)FindResource("Selection"),Opacity=.45,IsHitTestVisible=false};Canvas.SetLeft(caret,(PaperMargin+(ci%cols)*PaperCell)*_paperZoom);Canvas.SetTop(caret,(PaperMargin+(ci/cols)*PaperCell)*_paperZoom);canvas.Children.Add(caret);}for(int i=0;i<perPage;i++){var idx=p*perPage+i;if(idx>=chars.Length)break;var tb=new TextBlock{Text=chars[idx].ToString(),FontFamily=new FontFamily("Batang"),FontSize=Math.Max(7,17*_paperZoom),Foreground=(Brush)FindResource("Text"),Width=PaperCell*_paperZoom,Height=PaperCell*_paperZoom,TextAlignment=TextAlignment.Center,IsHitTestVisible=false};Canvas.SetLeft(tb,(PaperMargin+(i%cols)*PaperCell)*_paperZoom);Canvas.SetTop(tb,(PaperMargin+(i/cols)*PaperCell)*_paperZoom+Math.Max(0,(PaperCell*_paperZoom-tb.FontSize*1.35)/2));canvas.Children.Add(tb);}var pn=new TextBlock{Text=$"{p+1}",Foreground=(Brush)FindResource("Muted"),FontSize=Math.Max(8,10*_paperZoom),IsHitTestVisible=false};Canvas.SetLeft(pn,(logicalW/2)*_paperZoom);Canvas.SetTop(pn,(logicalH-24)*_paperZoom);canvas.Children.Add(pn);ManuscriptPaperHost.Children.Add(canvas);}}
 void ThemeToggle_Click(object s,RoutedEventArgs e)=>ApplyTheme(!_dark);
 void ApplyTheme(bool dark){
  _dark=dark;
  SetBrush("Bg",dark?"#181B1F":"#E8EBEF"); SetBrush("Surface",dark?"#20242A":"#F5F6F8");
  SetBrush("Panel",dark?"#242930":"#EEF1F4"); SetBrush("Panel2",dark?"#2B3139":"#FFFFFF");
  SetBrush("EditorBg",dark?"#1D2126":"#FFFFFF"); SetBrush("Text",dark?"#E6E9ED":"#20242A");
  SetBrush("Muted",dark?"#939BA6":"#66707C"); SetBrush("Border",dark?"#343B45":"#D4D9E0");
  SetBrush("Accent",dark?"#70A9E8":"#2F72B7"); SetBrush("Selection",dark?"#304B68":"#BFD9F4"); SetBrush("TabSelected",dark?"#1E2227":"#E1E5EA");
  ThemeGlyph.Text=dark?"☾ Dark":"☀ Light"; ThemeGlyph.Foreground=(Brush)FindResource("Text"); ThemeToggle.Foreground=(Brush)FindResource("Text"); ThemeToggle.Background=(Brush)FindResource("Panel2"); ThemeToggle.IsChecked=!dark; _document.Settings.Theme=dark?"dark":"light"; ApplyWindowChromeTheme();
 }
 void ApplyWindowChromeTheme(){if(!IsInitialized)return;try{var hwnd=new WindowInteropHelper(this).Handle;if(hwnd==IntPtr.Zero)return;int value=_dark?1:0;DwmSetWindowAttribute(hwnd,20,ref value,sizeof(int));}catch{}}
 [DllImport("dwmapi.dll")] static extern int DwmSetWindowAttribute(IntPtr hwnd,int attribute,ref int value,int size);
 void SetBrush(string key,string hex)=>Application.Current.Resources[key]=new SolidColorBrush((Color)ColorConverter.ConvertFromString(hex));
}
